variables:
  TERM: linux
  JULIA_VERSION: 1.6.2
  JULIA: /usr/local/julia/$JULIA_VERSION/bin/julia

stages:
  - test

unit_tests:
  stage: test
  script:
    - $JULIA --project=@. -e "import Pkg; Pkg.Registry.update(); Pkg.test()"
