style = "yas"
align_assignment = true
whitespace_in_kwargs = true
whitespace_ops_in_indices = false
pipe_to_function_call = false
align_struct_field = true
align_pair_arrow = true
align_conditional = true
