name = "FastLapackInterface"
uuid = "29a986be-02c6-4525-aec4-84b980013641"
authors = ["Louis Ponet, Michel Juillard"]
version = "1.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "^1.6.3"
